namespace: ansible
name: amazon
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: null
repository: git@github.com:ansible-collections/ansible.amazon.git
documentation: null
homepage: null
issues: null
